"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
const cache = require("./cache");
exports.cache = cache;
const config = require("./config");
exports.config = config;
const database = require("./database");
exports.database = database;
const arango_1 = require("./database/provider/arango");
exports.arango = arango_1.create;
const nedb_1 = require("./database/provider/nedb");
exports.nedb = nedb_1.create;
const logger_1 = require("./logger");
exports.Logger = logger_1.Logger;
// import {Client as microserviceClient} from './microservice/client';
// export * from './microservice/client';
const server_1 = require("./microservice/server");
exports.Server = server_1.Server;
const endpoint_1 = require("./microservice/endpoint");
exports.endpoint = endpoint_1.chain;
const loadbalancer = require("./microservice/loadbalancer");
exports.loadbalancer = loadbalancer;
__export(require("./microservice/loadbalancer"));
const errors = require("./microservice/errors");
exports.errors = errors;
const grpc = require("./microservice/transport/provider/grpc");
exports.grpc = grpc;
// export {Client as grpcClient} from './microservice/transport/provider/grpc';
var grpc_1 = require("./microservice/transport/provider/grpc");
exports.grpcServer = grpc_1.Server;
const grpc_2 = require("./microservice/transport/provider/grpc");
exports.ServerReflection = grpc_2.ServerReflection;
var pipe_1 = require("./microservice/transport/provider/pipe");
exports.pipeServer = pipe_1.Server;
exports.pipeClient = pipe_1.Client;
const command_interface_1 = require("./command-interface");
exports.CommandInterface = command_interface_1.CommandInterface;
